// On-device ST7735 status display for the LilyGo T-Dongle-S3 / -C5 (0.96" IPS,
// driven in LANDSCAPE: 160x80). Both boards drive the same ST7735 panel (same
// init/gamma/INVON); only the SPI GPIOs, the MADCTL rotation byte, the RAM offsets
// and the backlight polarity differ — and those now come at RUNTIME from a board
// preset (display_board_preset() at the bottom of this file), chosen by the NVS
// `board` key. So ONE firmware image serves both a panel-less ESP32-S3 (board
// "generic" → display_start() is a no-op) and the T-Dongle-S3 (board "t-dongle-s3"),
// and there is a SINGLE OTA channel for every board. See display.hpp for the design
// contract; the layout mirrors tools/display_sim.py (the pixel-exact renderer) 1:1.

#include "display.hpp"

#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cmath>
#include <string>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/spi_master.h"
#include "driver/gpio.h"
#include "esp_heap_caps.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_rom_sys.h"   // esp_rom_delay_us — settle the probe pulls

#include "vehicle_ctrl.hpp"
#include "display_font.h"   // generated by tools/display_sim.py — font + BT/BOLT bitmaps

static const char* TAG = "display";

// Defined in main.cpp — true only while the STA holds an IP. The display task is
// created (display_start) BEFORE wifi_connect() and at higher priority than
// app_main, so without this guard it would call esp_wifi_sta_get_ap_info() while
// esp_wifi is still initialising / churning through association — a concurrent read
// of the half-built AP record faults (LoadProhibited, EXCVADDR=0x1). Not connected →
// the centre WiFi-search animation is shown instead (the correct state anyway).
bool wifi_is_connected();

// ─── panel geometry & runtime board config ───────────────────────────────────
// Landscape orientation: 160 wide x 80 tall (identical panel on both boards). The
// SPI pins, RAM offsets (e.g. landscape col 1 / row 26 for the 0.96" GREENTAB),
// MADCTL and backlight polarity vary per board, so they live in s_cfg, populated by
// display_start() from the selected DisplayConfig instead of compile-time Kconfig.
static constexpr int W = 160;
static constexpr int H = 80;
static DisplayConfig s_cfg;                       // set once in display_start()
static inline int BL_ON() { return s_cfg.bl_active_low ? 0 : 1; }

// ─── colours (RGB565, natural order; byte-swapped at flush) — DARK theme ──────
static inline uint16_t rgb565(uint8_t r, uint8_t g, uint8_t b) {
    return (uint16_t)(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
}
static const uint16_t C_BG      = rgb565( 13,  16,  22);   // near-black screen bg
static const uint16_t C_PANEL   = rgb565( 26,  32,  45);   // battery interior / empty
static const uint16_t C_BORDER  = rgb565(236, 238, 242);   // battery shell + terminal
static const uint16_t C_INK     = rgb565(240, 242, 245);   // primary text
static const uint16_t C_GREY    = rgb565(128, 138, 152);   // muted / disconnected
static const uint16_t C_DIV     = rgb565( 38,  46,  60);   // header divider
static const uint16_t C_BAR_ON  = rgb565( 74, 175,  80);   // lit signal bar (green)
static const uint16_t C_BAR_OFF = rgb565( 40,  50,  64);   // unlit signal bar
static const uint16_t C_BOLT    = rgb565(255, 235, 120);   // charging bolt (yellow)
// BLE "searching" bars sweep from light-green (resting) to a deep/dark green
// (highlight) — high contrast so the moving bar is obvious.
static const int C_BLE_LIGHT_RGB[3] = {170, 232, 158};
static const int C_BLE_GREEN_RGB[3] = { 16,  78,  36};

// red → amber → light-green → green → deep-green over SoC 0..100 (mirrors the sim)
struct GradStop { float p; uint8_t r, g, b; };
static const GradStop GRAD[] = {
    {0.00f, 231,  76,  60}, {0.18f, 240, 190,  40}, {0.45f, 120, 200,  90},
    {0.80f,  60, 175,  80}, {1.00f,  30, 140,  60},
};
static inline int lerp8(int a, int b, float t) { return a + (int)lroundf((b - a) * t); }
static void soc_rgb(int soc, int& r, int& g, int& b) {
    float p = soc <= 0 ? 0.0f : (soc >= 100 ? 1.0f : soc / 100.0f);
    const int n = sizeof(GRAD) / sizeof(GRAD[0]);
    for (int i = 0; i < n - 1; ++i) {
        if (p <= GRAD[i + 1].p) {
            float span = GRAD[i + 1].p - GRAD[i].p;
            float t = span <= 0 ? 0.0f : (p - GRAD[i].p) / span;
            r = lerp8(GRAD[i].r, GRAD[i + 1].r, t);
            g = lerp8(GRAD[i].g, GRAD[i + 1].g, t);
            b = lerp8(GRAD[i].b, GRAD[i + 1].b, t);
            return;
        }
    }
    r = GRAD[n - 1].r; g = GRAD[n - 1].g; b = GRAD[n - 1].b;
}

// ─── state ────────────────────────────────────────────────────────────────────
static spi_device_handle_t s_spi = nullptr;
static uint16_t*           s_fb  = nullptr;   // W*H framebuffer (PSRAM if present)

// ─── low-level SPI ──────────────────────────────────────────────────────────--
static void dc(int level) { gpio_set_level((gpio_num_t)s_cfg.dc, level); }

static void spi_tx(const uint8_t* data, size_t len) {
    if (!len) return;
    spi_transaction_t t = {};
    t.length    = len * 8;
    t.tx_buffer = data;
    spi_device_polling_transmit(s_spi, &t);
}
static void wr_cmd(uint8_t c)  { dc(0); spi_tx(&c, 1); }
static void wr_data(uint8_t d) { dc(1); spi_tx(&d, 1); }
static void wr_data_n(const uint8_t* d, size_t n) { dc(1); spi_tx(d, n); }

static void set_window(int x0, int y0, int x1, int y1) {
    uint8_t cax[4] = { 0, (uint8_t)(x0 + s_cfg.x_off), 0, (uint8_t)(x1 + s_cfg.x_off) };
    uint8_t ray[4] = { 0, (uint8_t)(y0 + s_cfg.y_off), 0, (uint8_t)(y1 + s_cfg.y_off) };
    wr_cmd(0x2A); wr_data_n(cax, 4);   // CASET
    wr_cmd(0x2B); wr_data_n(ray, 4);   // RASET
    wr_cmd(0x2C);                      // RAMWR
}

// Init sequence (commands, delays, gamma/power tables, INVON, COLMOD 0x05) is the
// one LilyGo ships for this panel — Xinyuan-LilyGO/T-Dongle-C5 st7735.cpp; the
// T-Dongle-S3 uses the identical ST7735 panel. MADCTL comes from Kconfig so the
// orientation can be tuned per board without a code change.
static void panel_init() {
    gpio_set_level((gpio_num_t)s_cfg.rst, 0); vTaskDelay(pdMS_TO_TICKS(20));
    gpio_set_level((gpio_num_t)s_cfg.rst, 1); vTaskDelay(pdMS_TO_TICKS(120));

    wr_cmd(0x01); vTaskDelay(pdMS_TO_TICKS(150));            // SWRESET
    wr_cmd(0x11); vTaskDelay(pdMS_TO_TICKS(255));            // SLPOUT

    uint8_t frm[3]  = { 0x01, 0x2C, 0x2D };
    wr_cmd(0xB1); wr_data_n(frm, 3);                        // FRMCTR1
    wr_cmd(0xB2); wr_data_n(frm, 3);                        // FRMCTR2
    uint8_t frm3[6] = { 0x01,0x2C,0x2D,0x01,0x2C,0x2D };
    wr_cmd(0xB3); wr_data_n(frm3, 6);                      // FRMCTR3
    wr_cmd(0xB4); wr_data(0x07);                           // INVCTR

    uint8_t pw1[3] = { 0xA2, 0x02, 0x84 };
    wr_cmd(0xC0); wr_data_n(pw1, 3);                       // PWCTR1
    wr_cmd(0xC1); wr_data(0xC5);                           // PWCTR2
    uint8_t pw3[2] = { 0x0A, 0x00 };
    wr_cmd(0xC2); wr_data_n(pw3, 2);                       // PWCTR3
    uint8_t pw4[2] = { 0x8A, 0x2A };
    wr_cmd(0xC3); wr_data_n(pw4, 2);                       // PWCTR4
    uint8_t pw5[2] = { 0x8A, 0xEE };
    wr_cmd(0xC4); wr_data_n(pw5, 2);                       // PWCTR5
    wr_cmd(0xC5); wr_data(0x0E);                           // VMCTR1

    wr_cmd(0x21);                                          // INVON (0.96" IPS)
    wr_cmd(0x36); wr_data(s_cfg.madctl);                  // MADCTL (landscape, per board preset)
    wr_cmd(0x3A); wr_data(0x05);                           // COLMOD: 16-bit/pixel

    uint8_t gp[16] = { 0x02,0x1c,0x07,0x12,0x37,0x32,0x29,0x2d,
                       0x29,0x25,0x2B,0x39,0x00,0x01,0x03,0x10 };
    wr_cmd(0xE0); wr_data_n(gp, 16);                       // GMCTRP1
    uint8_t gn[16] = { 0x03,0x1d,0x07,0x06,0x2E,0x2C,0x29,0x2D,
                       0x2E,0x2E,0x37,0x3F,0x00,0x00,0x02,0x10 };
    wr_cmd(0xE1); wr_data_n(gn, 16);                       // GMCTRN1

    wr_cmd(0x13); vTaskDelay(pdMS_TO_TICKS(10));            // NORON
    wr_cmd(0x29); vTaskDelay(pdMS_TO_TICKS(100));           // DISPON
}

// Push the whole framebuffer one row at a time through a DMA-capable bounce buffer
// — keeps the framebuffer in PSRAM (where present) and never DMAs from it.
static void flush() {
    static uint8_t line[W * 2];
    for (int y = 0; y < H; ++y) {
        const uint16_t* src = &s_fb[y * W];
        for (int x = 0; x < W; ++x) {
            line[x * 2]     = src[x] >> 8;     // hi byte first (big-endian panel)
            line[x * 2 + 1] = src[x] & 0xFF;
        }
        set_window(0, y, W - 1, y);
        wr_data_n(line, sizeof(line));
    }
}

// ─── framebuffer drawing ──────────────────────────────────────────────────────
static inline void put(int x, int y, uint16_t c) {
    if ((unsigned)x < (unsigned)W && (unsigned)y < (unsigned)H) s_fb[y * W + x] = c;
}
static void fill(uint16_t c) { for (int i = 0; i < W * H; ++i) s_fb[i] = c; }
static void rect(int x0, int y0, int x1, int y1, uint16_t c) {
    for (int y = y0; y < y1; ++y) for (int x = x0; x < x1; ++x) put(x, y, c);
}
// Hollow border of thickness t with the 4 hard corners nibbled to bg (softer look).
static void border(int x0, int y0, int x1, int y1, int t, uint16_t c) {
    rect(x0, y0, x1, y0 + t, c);
    rect(x0, y1 - t, x1, y1, c);
    rect(x0, y0, x0 + t, y1, c);
    rect(x1 - t, y0, x1, y1, c);
    put(x0, y0, C_BG); put(x1 - 1, y0, C_BG);
    put(x0, y1 - 1, C_BG); put(x1 - 1, y1 - 1, C_BG);
}

static int text_w(const char* s, int scale) { return (int)strlen(s) * 6 * scale; }

static void draw_char(int x, int y, char ch, uint16_t col, int scale) {
    if (ch < 0x20 || ch > 0x7E) ch = ' ';   // outside printable ASCII → blank
    const uint8_t* g = DISPLAY_FONT5X7[ch - 0x20];
    for (int c = 0; c < 5; ++c) {
        uint8_t colbits = g[c];
        for (int r = 0; r < 7; ++r) {
            if (colbits & (1 << r)) {
                for (int dy = 0; dy < scale; ++dy)
                    for (int dx = 0; dx < scale; ++dx)
                        put(x + c * scale + dx, y + r * scale + dy, col);
            }
        }
    }
}
static int draw_text(int x, int y, const char* s, uint16_t col, int scale) {
    for (; *s; ++s) { draw_char(x, y, *s, col, scale); x += 6 * scale; }
    return x;
}
// White-on-anything text: 4-neighbour outline in oc, then the glyph in col.
static void draw_text_outline(int x, int y, const char* s, uint16_t col, int scale, uint16_t oc) {
    draw_text(x - 1, y, s, oc, scale); draw_text(x + 1, y, s, oc, scale);
    draw_text(x, y - 1, s, oc, scale); draw_text(x, y + 1, s, oc, scale);
    draw_text(x, y, s, col, scale);
}
// Like draw_text but only sets pixels with cx0 <= px < cx1 (the SSID scroll window).
static void draw_text_clip(int x, int y, const char* s, uint16_t col, int scale,
                           int cx0, int cx1) {
    for (; *s; ++s) {
        char ch = (*s >= 0x20 && *s <= 0x7E) ? *s : ' ';
        const uint8_t* g = DISPLAY_FONT5X7[ch - 0x20];
        for (int c = 0; c < 5; ++c) {
            uint8_t colbits = g[c];
            for (int r = 0; r < 7; ++r) {
                if (colbits & (1 << r)) {
                    for (int dy = 0; dy < scale; ++dy)
                        for (int dx = 0; dx < scale; ++dx) {
                            int px = x + c * scale + dx;
                            if (px >= cx0 && px < cx1) put(px, y + r * scale + dy, col);
                        }
                }
            }
        }
        x += 6 * scale;
    }
}

// Row-major bitmap: bit (w-1-c) of rows[r] = pixel (col c, row r). Template so the
// 8-bit BT glyph and the 16-bit bolt share one routine.
template <typename T>
static void blit_rows(int x, int y, const T* rows, int w, int h, int scale, uint16_t col) {
    for (int r = 0; r < h; ++r) {
        T bits = rows[r];
        for (int c = 0; c < w; ++c) {
            if (bits & (1u << (w - 1 - c))) {
                for (int dy = 0; dy < scale; ++dy)
                    for (int dx = 0; dx < scale; ++dx)
                        put(x + c * scale + dx, y + r * scale + dy, col);
            }
        }
    }
}
template <typename T>
static void blit_rows_outline(int x, int y, const T* rows, int w, int h, int scale,
                              uint16_t col, uint16_t oc) {
    static const int N[8][2] = {{-1,0},{1,0},{0,-1},{0,1},{-1,-1},{1,1},{-1,1},{1,-1}};
    for (int i = 0; i < 8; ++i) blit_rows(x + N[i][0], y + N[i][1], rows, w, h, scale, oc);
    blit_rows(x, y, rows, w, h, scale, col);
}

// 4 ascending bars, bottom-aligned at y+14; lit in `on`, unlit dark.
static void signal_bars(int x, int y, int level, uint16_t on) {
    for (int i = 0; i < 4; ++i) {
        int bh = 4 + i * 3;
        uint16_t col = (i < level) ? on : C_BAR_OFF;
        rect(x + i * 4, y + (14 - bh), x + i * 4 + 3, y + 14, col);
    }
}

static int rssi_bars(int rssi) {
    if (rssi >= -55) return 4;
    if (rssi >= -65) return 3;
    if (rssi >= -75) return 2;
    if (rssi >= -85) return 1;
    return 0;
}

// "Searching for a connection" animation, drawn where the battery would be (no
// battery while disconnected): a link label on the left — a Bluetooth glyph for BLE,
// or the word "WiFi" for WiFi — and a compact, right-flush cluster of 5 ascending
// bars whose dark-green highlight sweeps across light-green bars to read as
// "scanning". The swept bars are identical for WiFi and BLE; only the label differs.
// Mirrors draw_search_bars()/draw_searching_* in tools/display_sim.py.
static constexpr int   SRCH_N = 5, SRCH_BW = 10, SRCH_GAP = 6, SRCH_X0 = 80, SRCH_BASE = 70;  // compact, right-flush
static constexpr int   SRCH_ICON_SCALE = 3;
static constexpr int   SRCH_BT_X = 24, SRCH_BT_Y = 36;      // Bluetooth glyph, off the left edge
static constexpr int   SRCH_STEPS = 3;                       // animation sub-frames per bar
static constexpr float SRCH_FALLOFF = 1.5f;                  // highlight width, in bars
static constexpr int   SRCH_HALF = (SRCH_N - 1) * SRCH_STEPS;   // one direction (small↔large)
static constexpr int   SRCH_CYCLE = 2 * SRCH_HALF;           // full ping-pong period

// The swept bars are identical for WiFi and BLE searches; the highlight ping-pongs
// (a triangle wave) out and back across them — not a one-way scan.
static void draw_search_bars(int frame) {
    int p = frame % SRCH_CYCLE;
    float hp = (p <= SRCH_HALF ? p : (SRCH_CYCLE - p)) / (float)SRCH_STEPS;
    for (int i = 0; i < SRCH_N; ++i) {
        int   h = 12 + i * 7;
        float d = fabsf(i - hp);
        float t = d >= SRCH_FALLOFF ? 0.0f : (1.0f - d / SRCH_FALLOFF);
        uint16_t col = rgb565(lerp8(C_BLE_LIGHT_RGB[0], C_BLE_GREEN_RGB[0], t),
                              lerp8(C_BLE_LIGHT_RGB[1], C_BLE_GREEN_RGB[1], t),
                              lerp8(C_BLE_LIGHT_RGB[2], C_BLE_GREEN_RGB[2], t));
        int x = SRCH_X0 + i * (SRCH_BW + SRCH_GAP);
        rect(x, SRCH_BASE - h, x + SRCH_BW, SRCH_BASE, col);
    }
}
// BLE search: a Bluetooth glyph left of the bars.
static void draw_searching_icon(int frame, const uint8_t* icon, int iw, int ih, int ix, int iy) {
    blit_rows(ix, iy, icon, iw, ih, SRCH_ICON_SCALE, C_INK);
    draw_search_bars(frame);
}
// WiFi search: the word "WiFi" left of the bars (clearer than a glyph here).
static void draw_searching_text(int frame, const char* s, int scale, int x, int y) {
    draw_text(x, y, s, C_INK, scale);
    draw_search_bars(frame);
}

// Shown (instead of the search bars) once a BLE link is up but pairing isn't done:
// big "Pairing" with an animated 0–3 dot ellipsis (fixed left so it doesn't jiggle).
static void draw_pairing(int frame) {
    int nd = (frame / 4) % 4;
    char buf[12];
    snprintf(buf, sizeof(buf), "Pairing%.*s", nd, "...");
    draw_text((W - text_w("Pairing...", 2)) / 2, 42, buf, C_INK, 2);
}

// Horizontal marquee for an over-long SSID: ping-pong (pause, scroll out to reveal
// the end, pause, scroll back) so the whole name is readable. Returns the left
// offset 0..span. Mirrors scroll_offset() in tools/display_sim.py.
static constexpr int SCROLL_PAUSE = 8;   // ticks paused at each end
static constexpr int SCROLL_SPEED = 2;   // px per tick
static int scroll_offset(int tick, int span) {
    if (span <= 0) return 0;
    int travel = (span + SCROLL_SPEED - 1) / SCROLL_SPEED;   // ticks to cover the span
    int period = 2 * SCROLL_PAUSE + 2 * travel;
    int p = tick % period;
    if (p < SCROLL_PAUSE) return 0;                          // pause at start
    if (p < SCROLL_PAUSE + travel) {                         // scroll out
        int o = (p - SCROLL_PAUSE) * SCROLL_SPEED;
        return o < span ? o : span;
    }
    if (p < 2 * SCROLL_PAUSE + travel) return span;          // pause at end
    int o = span - (p - 2 * SCROLL_PAUSE - travel) * SCROLL_SPEED;  // scroll back
    return o > 0 ? o : 0;
}

// ─── compose one frame from cached state (mirrors tools/display_sim.py) ────────
// Returns true when it drew something animated (search/pairing, or a scrolling
// SSID) so the task keeps refreshing fast. `tick` is a monotonic frame counter;
// `paired` = VehicleController::has_session(), sampled by the task (it hits NVS,
// so it's not called every frame).
static bool compose(VehicleController& v, int tick, bool paired) {
    fill(C_BG);

    ChargeStateResult cs = v.get_cached_charge();
    bool have_soc = cs.valid && cs.has_battery_level;
    VehicleController::LinkState ls = v.link_state();
    bool unreachable = (ls == VehicleController::LinkState::Unreachable);
    bool ble_connected = v.ble_connected();

    char buf[48];
    wifi_ap_record_t ap = {};
    // Only query esp_wifi once the STA holds an IP — never during init/association
    // churn (see wifi_is_connected() note above): avoids the concurrent-read fault.
    bool wifi_on = wifi_is_connected() && (esp_wifi_sta_get_ap_info(&ap) == ESP_OK);
    // Centre state, by priority: WiFi search > pairing > battery > BLE search bars.
    bool wifi_searching = !wifi_on;
    bool pairing = ble_connected && !paired;              // BLE link up but not yet paired
    bool battery_ok = !unreachable && have_soc;
    // BLE search bars appear ONLY when the car is out of range (no link, no data).
    bool ble_bars = !(wifi_searching || pairing || battery_ok);
    bool scrolling = false;

    // ── header (taller, more legible): WiFi bars + SSID (scale 2) | BT + bars ─
    // Hide whichever small indicator is the active search hero; the big centre
    // animation represents it instead. An over-long SSID scrolls (clipped marquee).
    if (!wifi_searching) {
        signal_bars(4, 4, rssi_bars(ap.rssi), C_BAR_ON);
        snprintf(buf, sizeof(buf), "%s", (const char*)ap.ssid);
        int avail = ble_bars ? (158 - 28) : (158 - 28 - 32);
        int tw = text_w(buf, 2);
        if (tw <= avail) {
            draw_text(28, 4, buf, C_INK, 2);
        } else {                                  // too long → horizontal marquee
            int off = scroll_offset(tick, tw - avail);
            draw_text_clip(28 - off, 4, buf, C_INK, 2, 28, 28 + avail);
            scrolling = true;
        }
    }
    if (!ble_bars) {
        int8_t brssi = 0;
        bool rssi_ok = ble_connected && v.ble_rssi(brssi);
        int bx = 158 - 16;                    // 4 bars * 4px
        signal_bars(bx, 4, rssi_ok ? rssi_bars(brssi) : 0, C_BAR_ON);
        blit_rows(bx - 13, 1, DISPLAY_BT_ROWS, DISPLAY_BT_W, DISPLAY_BT_H, 2,
                  ble_connected ? C_INK : C_GREY);    // BT glyph, scale 2
    }

    rect(3, 22, W - 3, 23, C_DIV);            // divider under the (taller) header

    // ── centre: WiFi search > pairing > battery > BLE search bars ────────────
    if (wifi_searching) {
        draw_searching_text(tick, "WiFi", 2, 14, 42);   // "WiFi" word, not a glyph
        return true;
    }
    if (pairing) { draw_pairing(tick); return true; }
    if (!battery_ok) {
        draw_searching_icon(tick, DISPLAY_BT_ROWS, DISPLAY_BT_W, DISPLAY_BT_H,
                            SRCH_BT_X, SRCH_BT_Y);
        return true;
    }

    // ── battery shell ───────────────────────────────────────────────────────
    const int bx0 = 6, by0 = 24, bx1 = 146, by1 = 74;
    rect(bx0 + 2, by0 + 2, bx1 - 2, by1 - 2, C_PANEL);   // interior
    border(bx0, by0, bx1, by1, 3, C_BORDER);             // shell
    rect(bx1, 40, bx1 + 6, 58, C_BORDER);                // + terminal nub
    const int ix0 = bx0 + 3, iy0 = by0 + 3, ix1 = bx1 - 3, iy1 = by1 - 3;
    const int iw = ix1 - ix0;

    int soc = (int)lroundf(cs.battery_level);
    if (soc < 0) soc = 0;
    if (soc > 100) soc = 100;
    bool asleep = (ls == VehicleController::LinkState::Asleep);
    bool charging = (cs.charging_state == "Charging");

    int rr, gg, bb; soc_rgb(soc, rr, gg, bb);
    if (asleep) {                              // blend the fill toward the panel
        rr = lerp8(rr, 26, 0.5f); gg = lerp8(gg, 32, 0.5f); bb = lerp8(bb, 45, 0.5f);
    }
    uint16_t fill_col = rgb565(rr, gg, bb);
    int fw = (int)lroundf(iw * soc / 100.0f);
    if (fw > 0) rect(ix0, iy0, ix0 + fw, iy1, fill_col);

    char num[8];
    snprintf(num, sizeof(num), "%d%%", soc);
    bool show_bolt = charging && soc < 100 && !asleep;

    if (show_bolt) {                           // centred group: [bolt][gap][NN%]
        int bw = DISPLAY_BOLT_W * 2, gap = 6;
        int grp = bw + gap + text_w(num, 3);
        int gx = (W - grp) / 2;
        blit_rows_outline(gx, (H + 18 - DISPLAY_BOLT_H * 2) / 2 - 2,
                          DISPLAY_BOLT_ROWS, DISPLAY_BOLT_W, DISPLAY_BOLT_H, 2, C_BOLT, C_BG);
        draw_text_outline(gx + bw + gap, 41, num, C_INK, 3, C_BG);
    } else {
        draw_text_outline((W - text_w(num, 3)) / 2, 41, num,
                          asleep ? C_GREY : C_INK, 3, C_BG);
    }

    if (asleep)
        draw_text((W - text_w("ASLEEP", 1)) / 2, 64, "ASLEEP", C_GREY, 1);
    return scrolling;   // battery view still needs fast refresh while the SSID scrolls
}

// ─── refresh task ──────────────────────────────────────────────────────────--
// `tick` is monotonic so animations (search sweep, pairing dots) and the SSID
// marquee advance smoothly. When compose() reports nothing animating we idle at
// 1 Hz; while something animates (incl. a scrolling SSID) we refresh fast (~8 fps).
static void display_task(void* arg) {
    VehicleController& v = *static_cast<VehicleController*>(arg);
    int tick = 0;
    bool paired = v.has_session();        // has_session() hits NVS — sample at ~1 Hz
    for (;;) {
        bool animating = compose(v, tick, paired);
        flush();
        ++tick;
        if (animating) {
            if (tick % 8 == 0) paired = v.has_session();    // ~1 Hz while animating
            vTaskDelay(pdMS_TO_TICKS(120));
        } else {
            paired = v.has_session();                       // 1 Hz on the slow tick
            vTaskDelay(pdMS_TO_TICKS(1000));
        }
    }
}

// Board presets: map the NVS `board` string to its panel wiring. A board with no
// display (or an unknown value) returns {enabled=false}. Add a new board here — no
// per-board firmware/OTA needed. Geometry/MADCTL/polarity were HW-verified on the
// T-Dongle-S3 (see boards history / display_sim.py); the C5 differs only in pins.
DisplayConfig display_board_preset(const char* board) {
    DisplayConfig c;                       // default: disabled (generic / unknown)
    if (board && strcmp(board, "t-dongle-s3") == 0) {
        c.enabled = true;
        c.mosi = 3; c.sck = 5; c.cs = 4; c.dc = 2; c.rst = 1; c.bl = 38;
        c.bl_active_low = true;            // GPIO38 backlight is active-low
        c.x_off = 1; c.y_off = 26; c.madctl = 0xA8;   // landscape, 180° (MY|MV|BGR)
    }
    return c;
}

// Auto-detect the board when NVS hasn't pinned one. The ST7735 itself can't be probed
// (its SDA is write-only — no MISO), but the LilyGo T-Dongle-S3 carries a TF-card socket
// wired to the S3's SDMMC bus with EXTERNAL pull-ups on all six lines (CMD=16, D0-D3 =
// 14/17/21/18, CLK=12); a bare ESP32-S3 leaves those GPIOs floating. So read each with an
// internal pull-DOWN: a pin still HIGH ⇒ an external pull-up holds it ⇒ the dongle. A
// majority vote (≥4/6) tolerates a stray pull without false-positiving. HW-verified: 6/6
// HIGH on a T-Dongle-S3, 0/6 on a generic ESP32-S3. These GPIOs are otherwise unused.
const char* display_detect_board() {
    static const gpio_num_t sd_pins[] = { GPIO_NUM_16, GPIO_NUM_14, GPIO_NUM_17,
                                          GPIO_NUM_21, GPIO_NUM_18, GPIO_NUM_12 };
    int pulled = 0;
    for (gpio_num_t p : sd_pins) {
        gpio_reset_pin(p);
        gpio_set_direction(p, GPIO_MODE_INPUT);
        gpio_set_pull_mode(p, GPIO_PULLDOWN_ONLY);
        esp_rom_delay_us(1000);            // let the weak internal pull settle
        if (gpio_get_level(p)) ++pulled;
        gpio_set_pull_mode(p, GPIO_FLOATING);
    }
    const char* board = (pulled >= 4) ? "t-dongle-s3" : "generic";
    ESP_LOGI(TAG, "board auto-detect: %d/6 SD pull-ups → %s", pulled, board);
    return board;
}

void display_start(VehicleController& vehicle, const DisplayConfig& cfg) {
    if (!cfg.enabled) return;              // panel-less board (generic) → no-op
    s_cfg = cfg;

    // Framebuffer in PSRAM where present (free on the C5's 8 MB); on a no-PSRAM
    // board (T-Dongle-S3) this falls back to ~25 KB of internal SRAM. Allocated only
    // when a display is actually selected, so a panel-less build costs no SRAM.
    s_fb = (uint16_t*)heap_caps_malloc(W * H * sizeof(uint16_t), MALLOC_CAP_SPIRAM);
    if (!s_fb) s_fb = (uint16_t*)heap_caps_malloc(W * H * sizeof(uint16_t), MALLOC_CAP_8BIT);
    if (!s_fb) { ESP_LOGE(TAG, "no memory for framebuffer — display disabled"); return; }

    gpio_config_t io = {};
    io.mode = GPIO_MODE_OUTPUT;
    io.pin_bit_mask = (1ULL << s_cfg.dc) | (1ULL << s_cfg.rst) | (1ULL << s_cfg.bl);
    gpio_config(&io);
    gpio_set_level((gpio_num_t)s_cfg.bl, BL_ON());   // backlight on (honours polarity)

    spi_bus_config_t bus = {};
    bus.mosi_io_num   = s_cfg.mosi;
    bus.miso_io_num   = -1;
    bus.sclk_io_num   = s_cfg.sck;
    bus.quadwp_io_num = -1;
    bus.quadhd_io_num = -1;
    bus.max_transfer_sz = W * 2 + 8;
    if (spi_bus_initialize(SPI2_HOST, &bus, SPI_DMA_CH_AUTO) != ESP_OK) {
        ESP_LOGE(TAG, "spi_bus_initialize failed — display disabled"); return;
    }
    spi_device_interface_config_t dev = {};
    dev.clock_speed_hz = 40 * 1000 * 1000;
    dev.mode           = 0;
    dev.spics_io_num   = s_cfg.cs;
    dev.queue_size     = 7;
    if (spi_bus_add_device(SPI2_HOST, &dev, &s_spi) != ESP_OK) {
        ESP_LOGE(TAG, "spi_bus_add_device failed — display disabled"); return;
    }

    panel_init();
    ESP_LOGI(TAG, "ST7735 %dx%d (landscape) up on SPI2 (MOSI%d SCK%d CS%d DC%d, MADCTL 0x%02X)",
             W, H, s_cfg.mosi, s_cfg.sck, s_cfg.cs, s_cfg.dc, s_cfg.madctl);

    // 6 KB stack: soft-float gradient lerp + snprintf framing — 4 KB would be tight.
    xTaskCreate(display_task, "display", 6144, &vehicle, 3, nullptr);
}
