// On-device ST7735 status display for the LilyGo T-Dongle-S3 / -C5 (0.96" IPS,
// driven in LANDSCAPE: 160x80). Both boards drive the same ST7735 panel (same
// init/gamma/INVON); only the SPI GPIOs, the MADCTL rotation byte and the RAM
// offsets differ, so all of those come from Kconfig per board.
// See display.hpp for the design contract. The layout mirrors tools/display_sim.py
// (the offline pixel-exact renderer) one-to-one. Disabled (no-op) unless the board
// build selects CONFIG_TESLA_DISPLAY_ENABLED.

#include "display.hpp"
#include "sdkconfig.h"

#if CONFIG_TESLA_DISPLAY_ENABLED

#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cmath>
#include <string>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/spi_master.h"
#include "driver/gpio.h"
#include "esp_heap_caps.h"
#include "esp_wifi.h"
#include "esp_log.h"

#include "vehicle_ctrl.hpp"
#include "display_font.h"   // generated by tools/display_sim.py — font + BT/BOLT bitmaps

static const char* TAG = "display";

// ─── panel geometry & pins (per-board via Kconfig; see boards/*.defaults) ──────
// Landscape orientation: 160 wide x 80 tall.
static constexpr int W = 160;
static constexpr int H = 80;
#define PIN_MOSI  CONFIG_TESLA_DISPLAY_SPI_MOSI
#define PIN_SCK   CONFIG_TESLA_DISPLAY_SPI_SCK
#define PIN_CS    CONFIG_TESLA_DISPLAY_CS
#define PIN_DC    CONFIG_TESLA_DISPLAY_DC
#define PIN_RST   CONFIG_TESLA_DISPLAY_RST
#define PIN_BL    CONFIG_TESLA_DISPLAY_BL
// ST7735S 0.96" panels are offset within the controller's 132x162 RAM. In
// landscape (MADCTL with MV set) CASET spans the 160 axis and RASET the 80 axis,
// so the visible window starts at column 1 / row 26 — the swap of the portrait
// (26 / 1) offsets. Cross-verified against LilyGo's drivers (TFT_eSPI rotation 1/3
// for the GREENTAB160x80 panel). Override per board if a panel revision differs.
#define X_OFF     CONFIG_TESLA_DISPLAY_X_OFFSET
#define Y_OFF     CONFIG_TESLA_DISPLAY_Y_OFFSET
#define MADCTL    CONFIG_TESLA_DISPLAY_MADCTL
// Backlight polarity: the T-Dongle-S3's GPIO38 backlight is active-low (drive it
// LOW to light the panel). Kconfig bool → 1 when set, undefined otherwise.
#if CONFIG_TESLA_DISPLAY_BL_ACTIVE_LOW
static constexpr int BL_ON = 0;
#else
static constexpr int BL_ON = 1;
#endif

// ─── colours (RGB565, natural order; byte-swapped at flush) — DARK theme ──────
static inline uint16_t rgb565(uint8_t r, uint8_t g, uint8_t b) {
    return (uint16_t)(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
}
static const uint16_t C_BG      = rgb565( 13,  16,  22);   // near-black screen bg
static const uint16_t C_PANEL   = rgb565( 26,  32,  45);   // battery interior / empty
static const uint16_t C_BORDER  = rgb565(236, 238, 242);   // battery shell + terminal
static const uint16_t C_INK     = rgb565(240, 242, 245);   // primary text
static const uint16_t C_GREY    = rgb565(128, 138, 152);   // muted / disconnected
static const uint16_t C_DIV     = rgb565( 38,  46,  60);   // header divider
static const uint16_t C_BAR_ON  = rgb565( 74, 175,  80);   // lit signal bar (green)
static const uint16_t C_BAR_OFF = rgb565( 40,  50,  64);   // unlit signal bar
static const uint16_t C_BOLT    = rgb565(255, 235, 120);   // charging bolt (yellow)
// BLE "searching" bars sweep from light-green (resting) to a deep/dark green
// (highlight) — high contrast so the moving bar is obvious.
static const int C_BLE_LIGHT_RGB[3] = {170, 232, 158};
static const int C_BLE_GREEN_RGB[3] = { 16,  78,  36};

// red → amber → light-green → green → deep-green over SoC 0..100 (mirrors the sim)
struct GradStop { float p; uint8_t r, g, b; };
static const GradStop GRAD[] = {
    {0.00f, 231,  76,  60}, {0.18f, 240, 190,  40}, {0.45f, 120, 200,  90},
    {0.80f,  60, 175,  80}, {1.00f,  30, 140,  60},
};
static inline int lerp8(int a, int b, float t) { return a + (int)lroundf((b - a) * t); }
static void soc_rgb(int soc, int& r, int& g, int& b) {
    float p = soc <= 0 ? 0.0f : (soc >= 100 ? 1.0f : soc / 100.0f);
    const int n = sizeof(GRAD) / sizeof(GRAD[0]);
    for (int i = 0; i < n - 1; ++i) {
        if (p <= GRAD[i + 1].p) {
            float span = GRAD[i + 1].p - GRAD[i].p;
            float t = span <= 0 ? 0.0f : (p - GRAD[i].p) / span;
            r = lerp8(GRAD[i].r, GRAD[i + 1].r, t);
            g = lerp8(GRAD[i].g, GRAD[i + 1].g, t);
            b = lerp8(GRAD[i].b, GRAD[i + 1].b, t);
            return;
        }
    }
    r = GRAD[n - 1].r; g = GRAD[n - 1].g; b = GRAD[n - 1].b;
}

// ─── state ────────────────────────────────────────────────────────────────────
static spi_device_handle_t s_spi = nullptr;
static uint16_t*           s_fb  = nullptr;   // W*H framebuffer (PSRAM if present)

// ─── low-level SPI ──────────────────────────────────────────────────────────--
static void dc(int level) { gpio_set_level((gpio_num_t)PIN_DC, level); }

static void spi_tx(const uint8_t* data, size_t len) {
    if (!len) return;
    spi_transaction_t t = {};
    t.length    = len * 8;
    t.tx_buffer = data;
    spi_device_polling_transmit(s_spi, &t);
}
static void wr_cmd(uint8_t c)  { dc(0); spi_tx(&c, 1); }
static void wr_data(uint8_t d) { dc(1); spi_tx(&d, 1); }
static void wr_data_n(const uint8_t* d, size_t n) { dc(1); spi_tx(d, n); }

static void set_window(int x0, int y0, int x1, int y1) {
    uint8_t cax[4] = { 0, (uint8_t)(x0 + X_OFF), 0, (uint8_t)(x1 + X_OFF) };
    uint8_t ray[4] = { 0, (uint8_t)(y0 + Y_OFF), 0, (uint8_t)(y1 + Y_OFF) };
    wr_cmd(0x2A); wr_data_n(cax, 4);   // CASET
    wr_cmd(0x2B); wr_data_n(ray, 4);   // RASET
    wr_cmd(0x2C);                      // RAMWR
}

// Init sequence (commands, delays, gamma/power tables, INVON, COLMOD 0x05) is the
// one LilyGo ships for this panel — Xinyuan-LilyGO/T-Dongle-C5 st7735.cpp; the
// T-Dongle-S3 uses the identical ST7735 panel. MADCTL comes from Kconfig so the
// orientation can be tuned per board without a code change.
static void panel_init() {
    gpio_set_level((gpio_num_t)PIN_RST, 0); vTaskDelay(pdMS_TO_TICKS(20));
    gpio_set_level((gpio_num_t)PIN_RST, 1); vTaskDelay(pdMS_TO_TICKS(120));

    wr_cmd(0x01); vTaskDelay(pdMS_TO_TICKS(150));            // SWRESET
    wr_cmd(0x11); vTaskDelay(pdMS_TO_TICKS(255));            // SLPOUT

    uint8_t frm[3]  = { 0x01, 0x2C, 0x2D };
    wr_cmd(0xB1); wr_data_n(frm, 3);                        // FRMCTR1
    wr_cmd(0xB2); wr_data_n(frm, 3);                        // FRMCTR2
    uint8_t frm3[6] = { 0x01,0x2C,0x2D,0x01,0x2C,0x2D };
    wr_cmd(0xB3); wr_data_n(frm3, 6);                      // FRMCTR3
    wr_cmd(0xB4); wr_data(0x07);                           // INVCTR

    uint8_t pw1[3] = { 0xA2, 0x02, 0x84 };
    wr_cmd(0xC0); wr_data_n(pw1, 3);                       // PWCTR1
    wr_cmd(0xC1); wr_data(0xC5);                           // PWCTR2
    uint8_t pw3[2] = { 0x0A, 0x00 };
    wr_cmd(0xC2); wr_data_n(pw3, 2);                       // PWCTR3
    uint8_t pw4[2] = { 0x8A, 0x2A };
    wr_cmd(0xC3); wr_data_n(pw4, 2);                       // PWCTR4
    uint8_t pw5[2] = { 0x8A, 0xEE };
    wr_cmd(0xC4); wr_data_n(pw5, 2);                       // PWCTR5
    wr_cmd(0xC5); wr_data(0x0E);                           // VMCTR1

    wr_cmd(0x21);                                          // INVON (0.96" IPS)
    wr_cmd(0x36); wr_data((uint8_t)MADCTL);                // MADCTL (landscape via Kconfig)
    wr_cmd(0x3A); wr_data(0x05);                           // COLMOD: 16-bit/pixel

    uint8_t gp[16] = { 0x02,0x1c,0x07,0x12,0x37,0x32,0x29,0x2d,
                       0x29,0x25,0x2B,0x39,0x00,0x01,0x03,0x10 };
    wr_cmd(0xE0); wr_data_n(gp, 16);                       // GMCTRP1
    uint8_t gn[16] = { 0x03,0x1d,0x07,0x06,0x2E,0x2C,0x29,0x2D,
                       0x2E,0x2E,0x37,0x3F,0x00,0x00,0x02,0x10 };
    wr_cmd(0xE1); wr_data_n(gn, 16);                       // GMCTRN1

    wr_cmd(0x13); vTaskDelay(pdMS_TO_TICKS(10));            // NORON
    wr_cmd(0x29); vTaskDelay(pdMS_TO_TICKS(100));           // DISPON
}

// Push the whole framebuffer one row at a time through a DMA-capable bounce buffer
// — keeps the framebuffer in PSRAM (where present) and never DMAs from it.
static void flush() {
    static uint8_t line[W * 2];
    for (int y = 0; y < H; ++y) {
        const uint16_t* src = &s_fb[y * W];
        for (int x = 0; x < W; ++x) {
            line[x * 2]     = src[x] >> 8;     // hi byte first (big-endian panel)
            line[x * 2 + 1] = src[x] & 0xFF;
        }
        set_window(0, y, W - 1, y);
        wr_data_n(line, sizeof(line));
    }
}

// ─── framebuffer drawing ──────────────────────────────────────────────────────
static inline void put(int x, int y, uint16_t c) {
    if ((unsigned)x < (unsigned)W && (unsigned)y < (unsigned)H) s_fb[y * W + x] = c;
}
static void fill(uint16_t c) { for (int i = 0; i < W * H; ++i) s_fb[i] = c; }
static void rect(int x0, int y0, int x1, int y1, uint16_t c) {
    for (int y = y0; y < y1; ++y) for (int x = x0; x < x1; ++x) put(x, y, c);
}
// Hollow border of thickness t with the 4 hard corners nibbled to bg (softer look).
static void border(int x0, int y0, int x1, int y1, int t, uint16_t c) {
    rect(x0, y0, x1, y0 + t, c);
    rect(x0, y1 - t, x1, y1, c);
    rect(x0, y0, x0 + t, y1, c);
    rect(x1 - t, y0, x1, y1, c);
    put(x0, y0, C_BG); put(x1 - 1, y0, C_BG);
    put(x0, y1 - 1, C_BG); put(x1 - 1, y1 - 1, C_BG);
}

static int text_w(const char* s, int scale) { return (int)strlen(s) * 6 * scale; }

static void draw_char(int x, int y, char ch, uint16_t col, int scale) {
    if (ch < 0x20 || ch > 0x7E) ch = ' ';   // outside printable ASCII → blank
    const uint8_t* g = DISPLAY_FONT5X7[ch - 0x20];
    for (int c = 0; c < 5; ++c) {
        uint8_t colbits = g[c];
        for (int r = 0; r < 7; ++r) {
            if (colbits & (1 << r)) {
                for (int dy = 0; dy < scale; ++dy)
                    for (int dx = 0; dx < scale; ++dx)
                        put(x + c * scale + dx, y + r * scale + dy, col);
            }
        }
    }
}
static int draw_text(int x, int y, const char* s, uint16_t col, int scale) {
    for (; *s; ++s) { draw_char(x, y, *s, col, scale); x += 6 * scale; }
    return x;
}
// White-on-anything text: 4-neighbour outline in oc, then the glyph in col.
static void draw_text_outline(int x, int y, const char* s, uint16_t col, int scale, uint16_t oc) {
    draw_text(x - 1, y, s, oc, scale); draw_text(x + 1, y, s, oc, scale);
    draw_text(x, y - 1, s, oc, scale); draw_text(x, y + 1, s, oc, scale);
    draw_text(x, y, s, col, scale);
}

// Row-major bitmap: bit (w-1-c) of rows[r] = pixel (col c, row r). Template so the
// 8-bit BT glyph and the 16-bit bolt share one routine.
template <typename T>
static void blit_rows(int x, int y, const T* rows, int w, int h, int scale, uint16_t col) {
    for (int r = 0; r < h; ++r) {
        T bits = rows[r];
        for (int c = 0; c < w; ++c) {
            if (bits & (1u << (w - 1 - c))) {
                for (int dy = 0; dy < scale; ++dy)
                    for (int dx = 0; dx < scale; ++dx)
                        put(x + c * scale + dx, y + r * scale + dy, col);
            }
        }
    }
}
template <typename T>
static void blit_rows_outline(int x, int y, const T* rows, int w, int h, int scale,
                              uint16_t col, uint16_t oc) {
    static const int N[8][2] = {{-1,0},{1,0},{0,-1},{0,1},{-1,-1},{1,1},{-1,1},{1,-1}};
    for (int i = 0; i < 8; ++i) blit_rows(x + N[i][0], y + N[i][1], rows, w, h, scale, oc);
    blit_rows(x, y, rows, w, h, scale, col);
}

// 4 ascending bars, bottom-aligned at y+10; lit in `on`, unlit dark.
static void signal_bars(int x, int y, int level, uint16_t on) {
    for (int i = 0; i < 4; ++i) {
        int bh = 3 + i * 2;
        uint16_t col = (i < level) ? on : C_BAR_OFF;
        rect(x + i * 4, y + (10 - bh), x + i * 4 + 3, y + 10, col);
    }
}

static int rssi_bars(int rssi) {
    if (rssi >= -55) return 4;
    if (rssi >= -65) return 3;
    if (rssi >= -75) return 2;
    if (rssi >= -85) return 1;
    return 0;
}

// "Searching for a connection" animation, drawn where the battery would be (no
// battery while disconnected): a link icon (Bluetooth or WiFi) on the left and a
// compact, right-flush cluster of 5 ascending bars; a dark-green highlight sweeps
// across light-green bars (a flowing colour gradient) to read as "scanning". The
// swept bars are identical for WiFi and BLE — only the icon differs.
// Mirrors draw_searching() in tools/display_sim.py.
static constexpr int   SRCH_N = 5, SRCH_BW = 10, SRCH_GAP = 6, SRCH_X0 = 80, SRCH_BASE = 70;  // compact, right-flush
static constexpr int   SRCH_ICON_SCALE = 3;
static constexpr int   SRCH_BT_X = 24, SRCH_BT_Y = 36;      // Bluetooth glyph, off the left edge
static constexpr int   SRCH_WIFI_X = 16, SRCH_WIFI_Y = 38;  // WiFi glyph (wider), off the left edge
static constexpr int   SRCH_STEPS = 3;                       // animation sub-frames per bar
static constexpr float SRCH_FALLOFF = 1.5f;                  // highlight width, in bars
static constexpr int   SRCH_HALF = (SRCH_N - 1) * SRCH_STEPS;   // one direction (small↔large)
static constexpr int   SRCH_CYCLE = 2 * SRCH_HALF;           // full ping-pong period

static void draw_searching(int frame, const uint8_t* icon, int iw, int ih, int ix, int iy) {
    blit_rows(ix, iy, icon, iw, ih, SRCH_ICON_SCALE, C_INK);  // which link is being searched
    // The highlight ping-pongs smallest↔largest bar (a triangle wave): out and back.
    int p = frame % SRCH_CYCLE;
    float hp = (p <= SRCH_HALF ? p : (SRCH_CYCLE - p)) / (float)SRCH_STEPS;
    for (int i = 0; i < SRCH_N; ++i) {
        int   h = 12 + i * 7;
        float d = fabsf(i - hp);
        float t = d >= SRCH_FALLOFF ? 0.0f : (1.0f - d / SRCH_FALLOFF);
        uint16_t col = rgb565(lerp8(C_BLE_LIGHT_RGB[0], C_BLE_GREEN_RGB[0], t),
                              lerp8(C_BLE_LIGHT_RGB[1], C_BLE_GREEN_RGB[1], t),
                              lerp8(C_BLE_LIGHT_RGB[2], C_BLE_GREEN_RGB[2], t));
        int x = SRCH_X0 + i * (SRCH_BW + SRCH_GAP);
        rect(x, SRCH_BASE - h, x + SRCH_BW, SRCH_BASE, col);
    }
}

// Truncate s in place with a trailing '.' if it would exceed maxpx at scale 1.
static void fit(char* s, int maxpx) {
    int n = (int)strlen(s);
    if (n * 6 <= maxpx) return;
    int keep = maxpx / 6;
    if (keep < 1) { s[0] = '\0'; return; }
    s[keep - 1] = '.';
    s[keep]     = '\0';
}

// ─── compose one frame from cached state (mirrors tools/display_sim.py) ────────
// Returns true when it drew the searching animation (the task then animates fast).
static bool compose(VehicleController& v, int frame) {
    fill(C_BG);

    ChargeStateResult cs = v.get_cached_charge();
    bool have_soc = cs.valid && cs.has_battery_level;
    VehicleController::LinkState ls = v.link_state();
    bool unreachable = (ls == VehicleController::LinkState::Unreachable);

    char buf[48];
    wifi_ap_record_t ap = {};
    bool wifi_on = (esp_wifi_sta_get_ap_info(&ap) == ESP_OK);
    // What's being searched. WiFi has priority when both are down.
    bool wifi_searching = !wifi_on;
    bool ble_searching = unreachable || !have_soc;
    bool ble_is_hero = ble_searching && !wifi_searching;   // BLE shown as the hero search

    // ── header: WiFi bars + SSID (left) | BLE symbol + bars (right) ──────────
    // Each side is hidden while it is the active (hero) search — the big centre
    // animation represents it instead.
    if (!wifi_searching) {
        signal_bars(4, 3, rssi_bars(ap.rssi), C_BAR_ON);
        snprintf(buf, sizeof(buf), "%s", (const char*)ap.ssid);
        fit(buf, ble_is_hero ? (158 - 26) : (158 - 26 - 36));
        draw_text(26, 4, buf, C_INK, 1);
    }
    if (!ble_is_hero) {
        int8_t brssi = 0;
        bool ble_on = v.ble_connected() && v.ble_rssi(brssi);
        int bx = 158 - 16;                    // 4 bars * 4px
        signal_bars(bx, 3, ble_on ? rssi_bars(brssi) : 0, C_BAR_ON);
        blit_rows(bx - 9, 2, DISPLAY_BT_ROWS, DISPLAY_BT_W, DISPLAY_BT_H, 1,
                  ble_on ? C_INK : C_GREY);
    }

    rect(3, 17, W - 3, 18, C_DIV);            // divider under the header

    // ── searching: big animated bars instead of the battery (WiFi > BLE) ────
    if (wifi_searching) {
        draw_searching(frame, DISPLAY_WIFI_ROWS, DISPLAY_WIFI_W, DISPLAY_WIFI_H,
                       SRCH_WIFI_X, SRCH_WIFI_Y);
        return true;
    }
    if (ble_searching) {
        draw_searching(frame, DISPLAY_BT_ROWS, DISPLAY_BT_W, DISPLAY_BT_H,
                       SRCH_BT_X, SRCH_BT_Y);
        return true;
    }

    // ── battery shell ───────────────────────────────────────────────────────
    const int bx0 = 6, by0 = 24, bx1 = 146, by1 = 74;
    rect(bx0 + 2, by0 + 2, bx1 - 2, by1 - 2, C_PANEL);   // interior
    border(bx0, by0, bx1, by1, 3, C_BORDER);             // shell
    rect(bx1, 40, bx1 + 6, 58, C_BORDER);                // + terminal nub
    const int ix0 = bx0 + 3, iy0 = by0 + 3, ix1 = bx1 - 3, iy1 = by1 - 3;
    const int iw = ix1 - ix0;

    int soc = (int)lroundf(cs.battery_level);
    if (soc < 0) soc = 0;
    if (soc > 100) soc = 100;
    bool asleep = (ls == VehicleController::LinkState::Asleep);
    bool charging = (cs.charging_state == "Charging");

    int rr, gg, bb; soc_rgb(soc, rr, gg, bb);
    if (asleep) {                              // blend the fill toward the panel
        rr = lerp8(rr, 26, 0.5f); gg = lerp8(gg, 32, 0.5f); bb = lerp8(bb, 45, 0.5f);
    }
    uint16_t fill_col = rgb565(rr, gg, bb);
    int fw = (int)lroundf(iw * soc / 100.0f);
    if (fw > 0) rect(ix0, iy0, ix0 + fw, iy1, fill_col);

    char num[8];
    snprintf(num, sizeof(num), "%d%%", soc);
    bool show_bolt = charging && soc < 100 && !asleep;

    if (show_bolt) {                           // centred group: [bolt][gap][NN%]
        int bw = DISPLAY_BOLT_W * 2, gap = 6;
        int grp = bw + gap + text_w(num, 3);
        int gx = (W - grp) / 2;
        blit_rows_outline(gx, (H + 18 - DISPLAY_BOLT_H * 2) / 2 - 2,
                          DISPLAY_BOLT_ROWS, DISPLAY_BOLT_W, DISPLAY_BOLT_H, 2, C_BOLT, C_BG);
        draw_text_outline(gx + bw + gap, 41, num, C_INK, 3, C_BG);
    } else {
        draw_text_outline((W - text_w(num, 3)) / 2, 41, num,
                          asleep ? C_GREY : C_INK, 3, C_BG);
    }

    if (asleep)
        draw_text((W - text_w("ASLEEP", 1)) / 2, 64, "ASLEEP", C_GREY, 1);
    return false;
}

// ─── refresh task ──────────────────────────────────────────────────────────--
// Steady states refresh once a second; the BLE "searching" animation refreshes
// fast (~8 fps) and advances a frame counter so the highlight sweeps smoothly.
static void display_task(void* arg) {
    VehicleController& v = *static_cast<VehicleController*>(arg);
    int frame = 0;
    for (;;) {
        bool animating = compose(v, frame);
        flush();
        if (animating) {
            ++frame;
            vTaskDelay(pdMS_TO_TICKS(120));
        } else {
            frame = 0;
            vTaskDelay(pdMS_TO_TICKS(1000));
        }
    }
}

void display_start(VehicleController& vehicle) {
    // Framebuffer in PSRAM where present (free on the C5's 8 MB); on a no-PSRAM
    // board (T-Dongle-S3) this falls back to ~25 KB of internal SRAM.
    s_fb = (uint16_t*)heap_caps_malloc(W * H * sizeof(uint16_t), MALLOC_CAP_SPIRAM);
    if (!s_fb) s_fb = (uint16_t*)heap_caps_malloc(W * H * sizeof(uint16_t), MALLOC_CAP_8BIT);
    if (!s_fb) { ESP_LOGE(TAG, "no memory for framebuffer — display disabled"); return; }

    gpio_config_t io = {};
    io.mode = GPIO_MODE_OUTPUT;
    io.pin_bit_mask = (1ULL << PIN_DC) | (1ULL << PIN_RST) | (1ULL << PIN_BL);
    gpio_config(&io);
    gpio_set_level((gpio_num_t)PIN_BL, BL_ON);   // backlight on (BL_ON honours polarity)

    spi_bus_config_t bus = {};
    bus.mosi_io_num   = PIN_MOSI;
    bus.miso_io_num   = -1;
    bus.sclk_io_num   = PIN_SCK;
    bus.quadwp_io_num = -1;
    bus.quadhd_io_num = -1;
    bus.max_transfer_sz = W * 2 + 8;
    if (spi_bus_initialize(SPI2_HOST, &bus, SPI_DMA_CH_AUTO) != ESP_OK) {
        ESP_LOGE(TAG, "spi_bus_initialize failed — display disabled"); return;
    }
    spi_device_interface_config_t dev = {};
    dev.clock_speed_hz = 40 * 1000 * 1000;
    dev.mode           = 0;
    dev.spics_io_num   = PIN_CS;
    dev.queue_size     = 7;
    if (spi_bus_add_device(SPI2_HOST, &dev, &s_spi) != ESP_OK) {
        ESP_LOGE(TAG, "spi_bus_add_device failed — display disabled"); return;
    }

    panel_init();
    ESP_LOGI(TAG, "ST7735 %dx%d (landscape) up on SPI2 (MOSI%d SCK%d CS%d DC%d, MADCTL 0x%02X)",
             W, H, PIN_MOSI, PIN_SCK, PIN_CS, PIN_DC, (uint8_t)MADCTL);

    // 6 KB stack: soft-float gradient lerp + snprintf framing — 4 KB would be tight.
    xTaskCreate(display_task, "display", 6144, &vehicle, 3, nullptr);
}

#else  // !CONFIG_TESLA_DISPLAY_ENABLED

void display_start(VehicleController&) {}   // no panel on this board build

#endif
